---
galaxy_info:
  description: Install custom OpenStack Mistral, patched by StackStorm
  author: armab
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.2
  tags: st2mistral
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - automation
    - devops
    - workflows
dependencies:
  - role: postgresql
  - role: st2repos
