---

- name: Check if BWC license hash file is present
  stat:
    path: /etc/packagecloud/bwc_license_hash.txt
  register: bwc_license_hash_file
  tags:
    - BWC repos
    - StackStorm enterprise

- name: Read bwc_license_hash_file if it exits
  command: cat /etc/packagecloud/bwc_license_hash.txt
  register: _bwc_license_hash
  no_log: yes
  changed_when: no
  when: bwc_license_hash_file.stat.exists
  tags:
    - BWC repos
    - StackStorm enterprise

- name: Set bwc_license_hash from file context
  set_fact:
    bwc_license_hash: "{{ _bwc_license_hash.stdout }}"
  no_log: yes
  when: bwc_license_hash_file.stat.exists
  tags:
    - BWC repos
    - StackStorm enterprise

- name: Set bwc_license_hash to incoming hash if not defined
  no_log: yes
  set_fact:
    bwc_license_hash: '{{ bwc_license | hash("sha512") }}'
  when: not bwc_license_hash_file.stat.exists
  tags:
    - BWC repos
    - StackStorm enterprise

- name: Write bwc_license_hash to file if file not found on disk
  copy:
    content: "{{ bwc_license | hash('sha512') }}"
    dest: "/etc/packagecloud/bwc_license_hash.txt"
    force: yes
  become: yes
  when: not bwc_license_hash_file.stat.exists
  tags:
    - BWC repos
    - StackStorm enterprise

- name: "Cleanup read token cached file from disk"
  become: yes
  file:
    path: "/etc/packagecloud/StackStorm_{{ bwc_repo }}_read_token.txt"
    state: absent
  when: bwc_license | hash("sha512") != bwc_license_hash
  tags:
    - BWC repos
    - StackStorm enterprise

- name: "Cleanup repo list file from disk"
  become: yes
  include_tasks: "bwc_repos_cleanup_{{ ansible_facts.pkg_mgr }}.yml"
  when: bwc_license | hash("sha512") != bwc_license_hash
  tags:
    - BWC repos
    - StackStorm enterprise

- name: Write new bwc_license_hash to file
  copy:
    content: "{{ bwc_license | hash('sha512') }}"
    dest: "/etc/packagecloud/bwc_license_hash.txt"
    force: yes
  become: yes
  no_log: yes
  when: bwc_license | hash("sha512") != bwc_license_hash
  tags:
    - BWC repos
    - StackStorm enterprise
