---
- name: apt | Add mongodb key
  become: yes
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: 42F3E95A2C4F08279C4960ADD68FA50FEA312927
    state: present
  tags: [databases, mongodb]

- name: apt | Add mongodb repository
  become: yes
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }}/mongodb-org/3.2 multiverse'
    state: present
  tags: [databases, mongodb]

- name: apt | Install mongodb
  become: yes
  apt:
    name: mongodb-org
    update_cache: yes
    state: present
  notify:
    - Restart & Enable mongodb
  tags: [databases, mongodb]
