---
galaxy_info:
  description: Test EWC enteprise components were installed correctly.
  author: lakshmi-kannan
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - stackstorm
    - bwc
    - ewc
    - repositories
    - packagecloud
dependencies:
  - role: StackStorm.st2repo
  - role: StackStorm.st2
  - role: StackStorm.st2web
  - role: StackStorm.ewc
