---
rabbitmq_plugins: []
# To enable the management plugin (in which case you'd want at least one user tagged with administrator):
#rabbitmq_plugins:
#  - rabbitmq_management
# Set to "present" to install latest version, or specify specific version
rabbitmq_version: "present"
# Use version or wildcard
erlang_version: "{% if ansible_facts.os_family == 'Redhat' and ansible_facts.distribution_major_version == '8' %}24*{% elif ansible_facts.os_family == 'Debian' %}1.22.2.7+dfsg-1{% else %}present{% endif %}"
