---
sudo: required
dist: trusty
services: docker

branches:
  only:
    - master

env:
  - DISTRO=ubuntu-14
  - DISTRO=ubuntu-16
  - DISTRO=centos-6
  - DISTRO=centos-7

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - kitchen test ${DISTRO}
