---
galaxy_info:
  description: Install nginx org
  author: humblearner
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.2
  tags: nginx
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - web
    - nginx
