---
# Small suite of smoke tests to execute to ensure that the playbook has deployed as expected

- meta: flush_handlers
  tags:
    - smoke-tests

- name: Make sure packs are reloaded
  become: yes
  command: st2ctl reload --register-all
  changed_when: no
  tags:
    - smoke-tests

- name: st2 installed
  command: st2 --version
  changed_when: no
  tags:
    - smoke-tests

- name: get authentication token
  command: st2 auth "{{ st2_auth_username }}" -p "{{ st2_auth_password }}" -t
  register: st2_token
  changed_when: no
  tags:
    - smoke-tests

- name: st2 run core.local -- date -R
  command: st2 run core.local -- date -R
  environment:
    ST2_AUTH_TOKEN: "{{ st2_token.stdout }}"
  changed_when: no
  tags:
    - smoke-tests

- name: Check web-ui is up
  uri:
    url: https://localhost/
    validate_certs: no
  changed_when: no
  tags:
    - smoke-tests

- name: Install st2 pack from exchange
  become: yes
  environment:
    ST2_AUTH_TOKEN: "{{ st2_token.stdout }}"
  command: "st2 pack install st2"
  changed_when: no
  tags:
    - smoke-tests

- name: Verify st2chatops
  import_tasks: st2chatops.yml
  # st2chatops is installed
  when: st2chatops_version is defined
  tags:
    - smoke-tests
    - st2chatops
