- name: Sync database
  shell: /opt/openstack/mistral/.venv/bin/python ./tools/sync_db.py --config-file /etc/mistral/mistral.conf
  args:
    chdir: /opt/openstack/mistral
    creates: /etc/mistral/database_setup.lock
