---
galaxy_info:
  description: Install Nodejs
  author: humblearner
  company: StackStorm
  license: Apache
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - system
  dependencies:
    - role: epel
      when: ansible_os_family == 'RedHat'
