---
galaxy_info:
  description: Install StackStorm and all its components
  author: armab
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system
    - stackstorm
    - st2
    - automation
    - remediation
    - devops
dependencies:
  - role: StackStorm.epel
    when: ansible_facts.os_family == 'RedHat'
  - role: StackStorm.st2repo
