---
galaxy_info:
  description: Install EPEL repository
  author: mierdin
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - system
