---
galaxy_info:
  description: Install Rabbitmq-server
  author: humblearner
  company: StackStorm
  license: Apache
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system
