---

- name: Remove EWC smoke tests user from htpasswd file
  become: yes
  htpasswd:
    path: /etc/st2/htpasswd
    name: "{{ bwc_smoke_tests_user }}"
    state: absent
  changed_when: no
  notify:
    - reload bwc_rbac
  tags:
    - ewc-smoke-tests

- name: Remove RBAC smoke tests roles  # This doesn't cleanup role from DB.
  become: yes
  file:
    state: absent
    path: /opt/stackstorm/rbac/roles/{{ item.name }}.yml
  loop: "{{ bwc_smoke_tests_rbac.roles }}"
  when: bwc_smoke_tests_rbac.roles is defined
  changed_when: no
  notify:
    - reload bwc_rbac
  tags:
    - ewc-smoke-tests

- name: Remove RBAC smoke tests assignments  # This doesn't cleanup assignment from DB.
  become: yes
  file:
    state: absent
    path: /opt/stackstorm/rbac/assignments/{{ bwc_smoke_tests_user }}.yml
  when: bwc_smoke_tests_rbac.assignments is defined
  changed_when: no
  notify:
    - reload bwc_rbac
  tags:
    - ewc-smoke-tests
