---
galaxy_info:
  description: Install st2web
  author: humblearner
  company: StackStorm
  license: Apache
  min_ansible_version: 2.5
  tags: st2web
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system
dependencies:
  - role: StackStorm.nginx
  - role: StackStorm.st2repo
  - role: StackStorm.st2
