---
galaxy_info:
  description: Install PostgreSQL
  author: humblearner
  company: StackStorm
  license: Apache
  min_ansible_version: 2.2
  tags: [db, postgresql]
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
        - 6
        - 7
  categories:
    - system
