---
# Fixes "Failure talking to yum: Cannot retrieve repository metadata (repomd.xml) for repository: StackStorm_stable. Please verify its path and try again" when installing st2
- name: Update ca-certificates package
  become: yes
  yum:
    name: ca-certificates
    state: latest
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: [st2repo, skip_ansible_lint]

# See: https://github.com/docker-library/docs/tree/master/centos#package-documentation
# We ship `nginx.conf` via `st2` package doc files, for example
- name: Enable shipping package documentation files for EL
  become: yes
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: tsflags
    value: nodocs
    state: absent
  when: ansible_os_family == "RedHat"
  tags: st2repo

- name: Add StackStorm repo
  become: yes
  yum_repository:
    name: "StackStorm_{{ st2repo_name }}"
    description: "StackStorm_{{ st2repo_name }}"
    file: "StackStorm_{{ st2repo_name }}"
    baseurl: https://packagecloud.io/StackStorm/{{ st2repo_name }}/el/{{ ansible_distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgkey: "https://packagecloud.io/StackStorm/{{ st2repo_name }}/gpgkey"
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
    gpgcheck: no
    enabled: yes
    sslverify: yes
  tags: st2repo
