---
galaxy_info:
  description: Install StackStorm and all its components
  author: armab
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - stackstorm
    - st2
    - automation
    - remediation
    - devops
dependencies:
  - role: epel
    when: ansible_facts.os_family == 'RedHat'
  - role: st2repo
