---

# Fixes "Failure talking to yum: Cannot retrieve repository metadata (repomd.xml) for repository: StackStorm_stable. Please verify its path and try again" when installing st2
- name: Update ca-certificates package
  become: yes
  yum:
    name: ca-certificates
    state: latest
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags:
    - ewc
    - enterprise
    - skip_ansible_lint

- name: "Add packagecloud.io repository: StackStorm/{{ ewc_repo }}"
  become: yes
  no_log: yes
  yum_repository:
    name: "StackStorm_{{ ewc_repo }}"
    description: "StackStorm_{{ ewc_repo }}"
    file: "StackStorm_{{ ewc_repo }}"
    baseurl: https://{{ ewc_read_token }}:@packagecloud.io/StackStorm/{{ ewc_repo }}/el/{{ ansible_facts.distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgkey: "https://{{ ewc_read_token }}:@packagecloud.io/StackStorm/{{ ewc_repo }}/gpgkey"
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
    gpgcheck: no
    enabled: yes
    sslverify: yes
  register: added_ewc_rpm_repository
  tags:
    - ewc
    - enterprise
