---
galaxy_info:
  description: Install nginx org
  author: humblearner
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.5
  tags: nginx
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - web
    - nginx
