# StackStorm version checks and facts gathering
# TODO: Rework as lookup plugin when Ansible 2.0 available: https://groups.google.com/forum/#!msg/ansible-devel/MF4TY-wa9Ww/mL9sVSMd5DwJ
---
- name: version | Lookup literal version
  shell: >
    curl -Ss -q https://downloads.stackstorm.net/deb/pool/trusty_{{ st2_version }}/main/s/st2api/ |
    grep 'amd64.deb' |
    sed -e "s~.*>st2api_\(.*\)-.*<.*~\1~g" |
    sort --version-sort -r |
    uniq | head -n 1
  when: st2_version == 'stable' or st2_version == 'unstable'
  register: _st2_version
  delegate_to: 127.0.0.1
  changed_when: False
  tags: [st2, version]

- name: version | Save version number to install
  set_fact: _st2_version="{{ _st2_version.stdout | default(st2_version) }}"
  tags: [st2, version]

- name: version | Check that specified st2 version is available
  uri:
    url: "https://downloads.stackstorm.net/releases/st2/{{ _st2_version }}/"
    status_code: 200
  when: st2_version == _st2_version
  delegate_to: 127.0.0.1
  tags: [st2, version]

- name: version | Lookup StackStorm revision to install
  set_fact:
    _st2_revision: "{{ lookup('url', 'https://downloads.stackstorm.net/releases/st2/' + _st2_version + '/debs/' + st2_revision + '/VERSION.txt') }}"
  when: st2_revision == 'current'
  tags: [st2, version]

- name: version | Gather StackStorm package info
  command: dpkg -s st2common
  register: _st2_package_info
  changed_when: no
  tags: [st2, version]

- name: version | Check if StackStorm is already installed
  set_fact:
    _st2_is_installed: "{{ _st2_package_info.rc == 0 }}"
  tags: [st2, version]

- name: version | Get installed StackStorm version and revision
  set_fact:
    _st2_installed_version: "{{ _st2_package_info.stdout|regex_replace('[\\s\\S]*Version: (.*)-\\S+\\n[\\s\\S]*', '\\\\1') }}"
    _st2_installed_revision: "{{ _st2_package_info.stdout|regex_replace('[\\s\\S]*Version: \\S+-(.*)\\n[\\s\\S]*', '\\\\1') }}"
  when: _st2_is_installed
  tags: [st2, version]
