- name: auth | Install auth pre-reqs (Debian)
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-passlib
    - apache2-utils
  when: ansible_os_family == 'Debian'

- name: auth | Install auth pre-reqs (RedHat)
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-passlib
    - httpd-tools
  when: ansible_os_family == 'RedHat'

- name: auth | Create htpasswd file
  become: true
  htpasswd:
    path: /etc/st2/htpasswd
    name: "{{ st2_auth_username }}"
    password: "{{ st2_auth_password }}"
  notify:
    - restart st2api
    - restart st2stream

- name: auth | Enable authentication
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: auth
    option: enable
    value: True
    backup: yes
  notify:
    - restart st2api
    - restart st2stream

- name: auth | Create root's CLI configuration directory
  become: yes
  file:
    path: /root/.st2
    state: directory
  when: st2_save_credentials

- name: auth | Save credentials in CLI configuration file
  become: yes
  blockinfile:
    dest: /root/.st2/config
    create: yes
    mode: 0700
    owner: root
    group: root
    block: |
      [credentials]
      username = {{ st2_auth_username }}
      password = {{ st2_auth_password }}
  when: st2_save_credentials
