- name: Install auth pre-reqs (Debian)
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-passlib
    - apache2-utils
  when: ansible_os_family == 'Debian'

- name: Install epel-release repo (RedHat)
  become: yes
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install auth pre-reqs (RedHat)
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-passlib
    - httpd-tools
  when: ansible_os_family == 'RedHat'

- name: Create htpasswd file
  become: true
  htpasswd:
    path: /etc/st2/htpasswd
    name: "{{ st2_auth_username }}"
    password: "{{ st2_auth_password }}"
  notify:
    - restart st2api/st2stream

- name: Enable authentication
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: auth
    option: enable
    value: True
    backup: yes
  notify: 
    - restart st2api/st2stream
