---
- name: Make stackstorm encryption keys directory
  become: yes
  file:
    path: "{{ st2_datastore_key_file | dirname }}"
    state: directory
    mode: 0750
    owner: root
    group: st2

- name: Generate st2 encryption key
  become: yes
  command: st2-generate-symmetric-crypto-key --key-path {{ st2_datastore_key_file }}
  args:
    creates: "{{ st2_datastore_key_file }}"

- name: Fix permissions on datastore encryption key
  become: yes
  file:
    path: "{{ st2_datastore_key_file }}"
    mode: 0640
    owner: root
    group: st2

- name: Configure encryption key in st2.conf
  become: yes
  ini_file:
    path: /etc/st2/st2.conf
    section: keyvalue
    option: encryption_key_path
    value: "{{ st2_datastore_key_file }}"
  notify: restart st2api

